services:
  wireloft:
    build: .
    container_name: wireloft
    restart: no
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "8000:8000"
