services:
  dailywire:
    build: .
    container_name: dailywire-downloader
    restart: no
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    environment:
      - TZ=Europe/Amsterdam